version: "3"

services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - ./DockerData/postgres:/var/lib/postgresql/data
        # ports:
        #     - "9432:5432"
        env_file: 
            - pgenv.txt
    
    web:
        build: 
            context: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - env.txt
        depends_on:
            - db
        command: sh /code/docker-entrypoint.sh

    redis:
        image: redis:6.2-alpine
        command: redis-server

    celery:
        build:
            context: .
        env_file:
            - env.txt
        depends_on: 
            - web
            - redis
        command: sh /code/celery.sh
